# Rescue DAG file, created after running
#   the Cats_and_Dogs-0.dag DAG file
# Created 7/31/2020 05:15:27 UTC
# Rescue DAG version: 2.0.1 (partial)
#
# Total number of Nodes: 14
# Nodes premarked DONE: 10
# Nodes that failed: 1
#   stage_out_local_local_1_0,<ENDLIST>

DONE create_dir_Cats_and_Dogs_0_local
RETRY create_dir_Cats_and_Dogs_0_local 1
DONE stage_in_remote_local_1_0
RETRY stage_in_remote_local_1_0 1
DONE stage_in_remote_local_0_0
RETRY stage_in_remote_local_0_0 1
DONE stage_in_local_local_0_0
RETRY stage_in_local_local_0_0 1
DONE preprocess1_py_ID0000001
RETRY preprocess1_py_ID0000001 1
DONE Augmentation_py_ID0000002
RETRY Augmentation_py_ID0000002 1
DONE clean_up_local_level_3_0
RETRY clean_up_local_level_3_0 1
DONE stage_out_local_local_0_0
RETRY stage_out_local_local_0_0 1
RETRY stage_out_local_local_1_0 1
DONE register_local_0_0
RETRY register_local_0_0 1
DONE clean_up_local_level_4_0
RETRY clean_up_local_level_4_0 1
RETRY register_local_1_0 1
RETRY clean_up_local_level_5_0 1
RETRY cleanup_Cats_and_Dogs_0_local 1
