# Rescue DAG file, created after running
#   the checkpoint-wf-0.dag DAG file
# Created 7/20/2020 18:13:45 UTC
# Rescue DAG version: 2.0.1 (partial)
#
# Total number of Nodes: 9
# Nodes premarked DONE: 3
# Nodes that failed: 1
#   print_nums1_py_ID0000001,<ENDLIST>

DONE create_dir_checkpoint-wf_0_local
RETRY create_dir_checkpoint-wf_0_local 5
DONE stage_in_remote_local_0_0
RETRY stage_in_remote_local_0_0 5
DONE stage_in_local_local_0_0
RETRY stage_in_local_local_0_0 5
RETRY print_nums1_py_ID0000001 5
RETRY clean_up_local_level_3_0 5
RETRY stage_out_local_local_0_0 5
RETRY register_local_0_0 5
RETRY clean_up_local_level_4_0 5
RETRY cleanup_checkpoint-wf_0_local 5
